import { AppBar, Box, Button, Toolbar, Typography } from "@mui/material"
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <AppBar>
        <Toolbar>
        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            TODOリスト
          </Typography>
          <Button href="/" color="inherit" >Top</Button>
          <Button href="/topics" color="inherit" >リストを追加</Button>
        </Toolbar>
      </AppBar>

      <Box sx={{display: "flex",justifyContent: "center", maxWidth: "2xl", mx: "auto", p: 2 }}>
        <Box sx={{width: "80%", maxWidth: "100%", mx: "auto", mt: 8 }}>
          {children}
        </Box>
      </Box>
    </body>
  </html>
  )
}
